name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Build
              run: |
                  npm install
                  npm run build
                  npm run electron:build:$TARGET
              env:
                  TARGET: ${{ secrets.TARGET }}

            - name: Test
              run: |
                  npm run lint
                  npm run test
        env:
            PAT: ${{ secrets.PAT }}
