name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: 📦 Install Packages
              run: |
                  npm install

            - name: 🧪 Test
              run: |
                  npm run lint
                  npm run test

            - name: 🛠 Build
              run: |
                  npm run build
                  npm run electron:build:$TARGET
              env:
                  TARGET: ${{ secrets.TARGET }}
